
name: build/

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    name: build & push image to github container registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v3
      - name: authenticate to gh container registry 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build & push image
        uses: docker/build-push-action@v3
        with:
          push: true 
          tags: ghcr.io/jmousqueton/tor-socks-proxy:latest